version: '3'

volumes:
  postgres_users_data: {}

services:

  postgres-users:
    image: postgres:9.6.3-alpine
    volumes:
      - postgres_users_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres-users
      - POSTGRES_PASSWORD=UruQl8st

  users-service:
    container_name: users-service
    build: ./microservice-users
    volumes:
      - ./microservice-users:/app
    ports:
      - "8080:8080"
    links:
      - postgres-users
