version: '3'

volumes:
  postgres_users_data: {}
  postgres_posts_data: {}

services:

  #
  # Database service
  #
  postgres-users:
    image: postgres:9.6.3-alpine
    volumes:
      - postgres_users_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres-users
      - POSTGRES_PASSWORD=UruQl8st

  postgres-posts:
    image: postgres:9.6.3-alpine
    volumes:
      - postgres_posts_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres-posts
      - POSTGRES_PASSWORD=UruQl8st

  #
  # gateway service
  #
  gateway-service:
    build: ./microservice-gateway
    ports:
      - "80:80"
    links:
      - users-service
      - frontend-service

  #
  # application services
  #
  users-service:
    container_name: users-service
    build: ./microservice-users
    volumes:
      - ./microservice-users:/app
    ports:
      - "8080:8080"
    links:
      - postgres-users
    env_file:
      - users.env

  posts-service:
    container_name: posts-service
    build: ./microservice-posts
    volumes:
      - ./microservice-posts:/app
    ports:
      - "8070:8070"
    links:
      - postgres-posts
    env_file:
      - posts.env

  frontend-service:
    build: ./microservice-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./microservice-frontend:/app
      - ./microservice-frontend/node_modules:/app/node_modules
    env_file:
      - frontend.env
    links:
      - users-service
