version: '3'

volumes:
  postgres_users_data: {}
  postgres_posts_data: {}

services:

  #
  # Database service
  #
  users-postgres:
    image: postgres:9.6.3-alpine
    volumes:
      - postgres_users_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=users-postgres
      - POSTGRES_PASSWORD=UruQl8st

  posts-postgres:
    image: postgres:9.6.3-alpine
    volumes:
      - postgres_posts_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=posts-postgres
      - POSTGRES_PASSWORD=UruQl8st

  #
  # gateway service
  #
  gateway-service:
    build: ./microservice-gateway
    ports:
      - "80:80"
    links:
      - users-service
      - posts-service
      - frontend-service

  #
  # application services
  #
  users-service:
    container_name: users-service
    build: ./microservice-users
    volumes:
      - ./microservice-users:/app
    ports:
      - "8080:8080"
    links:
      - users-postgres
    env_file:
      - users.env

  posts-service:
    container_name: posts-service
    build: ./microservice-posts
    volumes:
      - ./microservice-posts:/app
    ports:
      - "8070:8070"
    links:
      - posts-postgres
    env_file:
      - posts.env

  frontend-service:
    build: ./microservice-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./microservice-frontend:/app
      - ./microservice-frontend/node_modules:/app/node_modules
    env_file:
      - frontend.env
    links:
      - users-service
